name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  test-js-parser:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'parser/js'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'parser/js/.nvmrc'
          cache: 'npm'
          cache-dependency-path: 'parser/js/package-lock.json'
      - run: npm ci
      - run: npm test
  test-js-fsst:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'encodings/fsst/js'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/Iron'
          cache: 'npm'
          cache-dependency-path: '**/**/**/package-lock.json'
      - run: npm ci
      - run: npm run test
  test-js-fastpfor:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'encodings/fastpfor/js'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/Iron'
          cache: 'npm'
          cache-dependency-path: '**/**/**/package-lock.json'
      - run: npm ci
      - run: npm run build
      - run: npm run test:unit
  test-java-converter:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    defaults:
      run:
        working-directory: 'converter/java'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: gradle/actions/setup-gradle@v3
      - name: Java converter tests
        run: ./gradlew test
      - name: Test running CLI
        run: |
          ./gradlew cli
          java -jar ./build/libs/mvt2mlt-1.0-SNAPSHOT.jar -mvt ../../test/fixtures/omt/mvt/10_530_682.mvt -dir output
          python -c 'import os; expected=66984; ts=os.path.getsize("output/10_530_682.mlt"); assert ts == expected, f"tile size changed from expected ({expected}), got: {ts}"'
