name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-evaluation-js:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'evaluation/js'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/Iron'
          cache: 'npm'
          cache-dependency-path: '**/**/package-lock.json'
      - run: npm ci
      - run: npm run build
      - run: npm test
  test-parser-js:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'parser/js'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/Iron'
          cache: 'npm'
          cache-dependency-path: '**/**/package-lock.json'
      - run: npm ci
      - run: npm run build
      - run: npm test