name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-java-converter-ubuntu:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'converter/java'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: gradle/actions/setup-gradle@v3
      - run: ./gradlew test
  test-java-converter-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: 'converter/java'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: gradle/actions/setup-gradle@v3
      - run: .\gradlew.bat test
